[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aya-cli"
version = "0.1.0"
description = "Mac-only CLI to install Tiny Aya GGUF and run OpenAI-compatible server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "huggingface_hub",
    "typer",
    "huggingface"
]

[project.scripts]
aya-cli = "aya_cli.cli:app"

[project.optional-dependencies]
dev = []

[tool.setuptools.packages.find]
where = ["src"]
